name: alang-clike-parser
version: '0.1.0'
category: Devel
author: Justus Adam
maintainer: dev@justus.science
copyright: © 2017 Justus Adam
license: OtherLicense
github: ohua-dev/alang-clike-parser
extra-source-files:
- README.md
ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NamedFieldPuns
- RecordWildCards
- ConstraintKinds
- StandaloneDeriving
- NoImplicitPrelude
dependencies:
- base >=4.7 && <5
- bytestring
- protolude
- ohua-core
library:
  source-dirs: src
  exposed-modules:
  - Ohua.Compat.Clike.Lexer
  - Ohua.Compat.Clike.Parser
  - Ohua.Compat.Clike.Types
  dependencies:
  - array
  - unordered-containers
  - monad-loops
  - recursion-schemes
  build-tools:
  - alex
  - happy
tests:
  alang-clike-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alang-clike-parser
    - hspec
