name: alang-clike-parser
version: '0.1.0.0'
category: Devel
author: Justus Adam
maintainer: dev@justus.science
copyright: © 2017 Justus Adam
license: OtherLicense
github: ohua-dev/alang-clike-parser
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Ohua.Compat.Clike.Lexer
  - Ohua.Compat.Clike.Parser
  - Ohua.Compat.Clike.Types
  dependencies:
  - base >=4.7 && <5
  - ohua-core
  - bytestring
  - array
  - unordered-containers
  - monad-loops
  - recursion-schemes
  - mtl
  build-tools:
  - alex
  - happy
tests:
  alang-clike-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - alang-clike-parser
    - hspec
    - ohua-core
    - bytestring
