flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: a0078912fbe8e8733561888f449314a3487bda5e
  extra-dep: true
  subdirs: [core]
extra-deps: []
resolver: lts-12.10
