flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 0205bb761d16c1137b025594d7da4ed4051d6faf
  extra-dep: true
extra-deps: []
resolver: lts-9.6
