flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: cc55e0fe5737311a1657e7ac1df2e93294e79f45
  extra-dep: true
  subdirs: [core]
extra-deps: []
resolver: lts-12.10
