flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 22a1187ae5d57cc935729b20a69f627cd773e6f3 
  extra-dep: true
extra-deps: []
resolver: lts-9.6
