flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 016217ef1c5300e7068230f811b97050653bc624
  extra-dep: true
extra-deps: []
resolver: lts-9.6
