flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: c41e558ec6a4041c573afd22782d5098cc70c16
  extra-dep: true
extra-deps: []
resolver: lts-12.10
