flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: f29a82cd8119a26ddd443324f4509d9c55e4e92f
  extra-dep: true
extra-deps: []
resolver: lts-12.10
